# config.yml
# support environment variables in .env file

# Default to True, change to False to open chrome while scrapping (warning, slow)
Headless: 

# Default to True
# Query_search open selenium to get the query result
# Detailed_search use http.get for every places in the query result
# Warning: each queries can get up to 120 places, not using proxy for Detailed_search will definitely hit bot detection in no time
Query_search_proxy: False
Detailed_search_proxy: 

# Proxy authentication
Proxy:
  Domain: ${PROXY_DOMAIN}
  Port: ${PROXY_PORT}
  User: ${PROXY_USER}
  Password: ${PROXY_PASSWORD}

# Query
# must be filled: i.e.restaurants, company registry
Category: perusahaan

# 'once' or 'loop' through data source based on address level below, currently not implemented yet but dont remove or change this value!
Scrape_address: loop

# Criteria for address data loop, if all are empty will loop the entirety of address table
# Enter places name for i.e 'Jawa Barat' in Province or 'Bandung' in City
Address_level:
  Province: 
  City: 
  District/subdistrict: 
  Ward/village: 

# default to external if type is not empty
Data_source:
  Local:
    Location: backend/data.db 
    Csv_location: backend/data_template.csv # will fill csv data to the database
    Xlsx_location: # will fill xlsx data to the database
    Address_table_name: randomized_address
  
  # currently only support MariaDb
  External:
    Type: mariadb
    Domain: ${SOURCE_EXTERNAL_DOMAIN}
    Port: ${SOURCE_EXTERNAL_PORT}
    User: ${SOURCE_EXTERNAL_USER}
    Password: ${SOURCE_EXTERNAL_PASSWORD}
    Database_name: scrape_google_map
    Address_table_name: randomized_address

# log level defaults to info for console and warning for file, this option will set for both
# debug level will also check for IP rotation per request
Log_level: 

# not implemented yet
Is_tor: 