# config.yml
# support environment variables in .env file

# Default to True, change to false to open chrome while scrapping (warning, it is slow)
Headless: 

# Proxy authentication, leave blank if not using proxy
Proxy:
  Domain: ${PROXY_DOMAIN}
  Port: ${PROXY_PORT}
  User: ${PROXY_USER}
  Password: ${PROXY_PASSWORD}

# Query
# must be filled: i.e.restaurants, company registry
Category: company registry

# 'once' or 'loop' through data source based on address level below, currently not implemented yet but dont remove or change this value!
Scrape_address: loop

# Criteria for address data loop, if all are empty will loop the entirety of address table
# Enter places name for i.e 'Jawa Barat' in Province or 'Bandung' in City
Address_level:
  Province: 
  City: 
  District/subdistrict: 
  Ward/village: 

Data_source:
  Local:
    Location: backend/data.db # needed, you can change but don't leave empty
    Csv_location: backend/data_template.csv # will fill csv data to the database
    Xlsx_location: # will fill xlsx data to the database
    Address_table_name: randomized_address # needed
  
  # currently only support MariaDb, ignored if local (location and address table name) is not empty
  External:
    Type: MariaDb
    Domain: ${SOURCE_EXTERNAL_DOMAIN}
    Port: ${SOURCE_EXTERNAL_PORT}
    User: ${SOURCE_EXTERNAL_USER}
    Password: ${SOURCE_EXTERNAL_PASSWORD}
    Database_name: scrape_google_map
    Address_table_name: randomized_address

# log level defaults to info for console and warning for file, this option will set for both
Log_level: 